#pragma once


#ifndef STATEDB_FEATURE_ITERATION
#	define STATEDB_FEATURE_ITERATION true
#endif

#ifndef STATEDB_FEATURE_RAM_MONITORING
#	define STATEDB_FEATURE_RAM_MONITORING true
#endif

#define STATEDB_CHANGES_TRACING_MODE_ALWAYS 2	// Always notify clients about new value
#define STATEDB_CHANGES_TRACING_MODE_DEMAND 1	// Don't notify but support CACHE_CHECK_CMD
#define STATEDB_CHANGES_TRACING_MODE_DISABLED 0 // Don't notify and don't support CACHE_CHECK_CMD

#ifndef STATEDB_CHANGES_TRACING_MODE
#	define STATEDB_CHANGES_TRACING_MODE STATEDB_CHANGES_TRACING_MODE_ALWAYS
#endif




